### ISSUE TITLE
Introduce security related linter and fix existing problems

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#103]
#### Reason/Context
There are some common security issues that can be found statically and we should make sure parser is 100% free of those.

#### Description
- add https://github.com/nodesecurity/eslint-plugin-security and configure with eslint
- fix all the issues reported by the linter. There are many but trivial where mainly it is about switching form object to map. Good issue to familiarize with the project structure

**Comment by magicmatatjahu** [comment]
@derberg Hello :) I investigated little time issue, added plugin and configured with project and about 95% of issues are false positives with errors like `detect-object-injection`, which means that from code we retrieve some data from object by custom key passed as argument to function like:

```js
  binding(name) {
    return this._json.bindings ? this._json.bindings[name] : null;
  }
```

I see several solutions:

1. Cast the variable to string like `key => String(key)`. It strange, but it fixes the problem, example:

```js
utils.createMapOfType = (obj, Type) => {
  const result = {};
  if (!obj) return result;

  Object.keys(obj).forEach(key => {
    result[String(key)] = new Type(String(key));
  });

  return result;
};

utils.getMapKeyOfType = (obj, key, Type) => {
  if (!obj) return null;
  const v = obj[String(key)];
  if (!v) return null;
  return new Type(v);
};
```

Also we must do casting in places like:

```js
  binding(name) {
    return this._json.bindings ? this._json.bindings[String(name)] : null;
  }
```

2. Cast objects to ES6 Map type in `createMapOfType` and `getMapKeyOfType` functions. In this case, we will make breaking change to people who use the library. Then each retrieve operation would have to be done using the `.get()` method.

3. Add annotation for lines for skipping checking like `/* esling-disable next-line security/detect-object-injection */` but this is very bad, because we would have to add such annotation in a dozen places.

What do you think?

**Comment by derberg** [comment]
@magicmatatjahu already on the PR ;)
