### ISSUE TITLE
Extend the components model with has-like functions

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#173]
#### Reason/Context

It would be very useful when working on docs/code generators to have a set of helper functions that let you easily determine if there is or not a specific component added to the `components` section of the AsyncAPI document and if it has any data. These components are not required and it is not required to have any data in them, so someone can add an empty object for example.

Many models already have useful functions like `hasDescription`.

#### Description

- Add missing functions to [Components model](https://github.com/asyncapi/parser-js/blob/master/lib/models/components.js):
  - hasMessages
  - hasSchemas
  - hasSecuritySchemes
  - hasParameters
  - hasCorrelationIds
  - hasOperationTraits
  - hasMessageTraits

  Example `hasParameter` function from [Channels model](https://github.com/asyncapi/parser-js/blob/master/lib/models/channel.js#L38-L43)
- Add missing tests [here](https://github.com/asyncapi/parser-js/blob/master/test/models/components_test.js). Example test is [here](https://github.com/asyncapi/parser-js/blob/master/test/models/channel_test.js#L11-L20)

**Comment by magicmatatjahu** [comment]
I think that another models like `Info` should also have `has*` functions (like `hasContact`, `hasLicense` etc) for all not required fields.

**Comment by magicmatatjahu** [comment]
I made a simple PR https://github.com/asyncapi/parser-js/pull/175 and I checked that some models haven't relevant `has*` function for optional fields, for example `Info` model should have `hasContact`, `hasLicense` etc functions. Also some has-like functions should check that in checking object whole fields are required. What does it mean? `contact` field in `Info` model can be nil (`null` or `undefined`), empty (has `{}` value) or be an object with fields. If we write AsyncAPI schema with 

```json
"info": {
    "contact": {}
}
``` 

then json-schema-parser won't throw error, because any field in contact object isn't required, so `{}` is correct, so `hasContact()` function should check if object is nil or empty, then return false.It should be checked/fixed in other models.

@derberg What do you think?

**Comment by derberg** [comment]
@magicmatatjahu I totally agree, we need to properly handle those not mandatory fields that could be empty

**Comment by derberg** [comment]
video about the issue https://youtu.be/Iqs_2BiNEEo?t=2060

**Comment by derberg** [comment]
@magicmatatjahu you can reopen your PR ;)

**Comment by magicmatatjahu** [comment]
@derberg I force pushes commits before reopen and I had to create the new one. https://github.com/asyncapi/parser-js/pull/192
