### ISSUE TITLE
`x-parser-original-payload` isn't the original payload with asyncapi schema parser

### ISSUE THREAD

**Issue by JQrdan** [asyncapi/parser-js#245]
Using something like `channel.subscribe().messages('myMessage').originalPayload();` will return a schema that has all of the `x-parser-schema-id` extensions baked in. This is not part of the original payload. This isn't an issue with the Avro schema parser as they remove the reference to `message.payload` for the original. 

We've managed to create a custom parser that gets around the issue:

```
import {cloneDeep} from 'lodash';

export default {
  parse: async ({ message, defaultSchemaFormat }) => {
    message['x-parser-original-schema-format'] = message.schemaFormat || defaultSchemaFormat;
    // keep copy of original payload without x-parser-schema-id extensions
    message['x-parser-original-payload'] = cloneDeep(message.payload);
    delete message.schemaFormat;
  },
  getMimeTypes: () => {
    return [
      'application/vnd.aai.asyncapi;version=2.0.0',
      'application/vnd.aai.asyncapi+json;version=2.0.0',
      'application/vnd.aai.asyncapi+yaml;version=2.0.0'
    ]
  }
};
```
cloneDeep was needed as it did set the original payload correctly without it, but then `message.payload` changed after the parser had been called so the original also changed with it.

Is this supposed to be how it works? We would like to be able to create a visualisation of the schema without all of the parser extensions included and this custom parser feels a bit sketchy.

**Comment by derberg** [comment]
This is a tricky topic. Just recently I discussed it in [this](https://github.com/asyncapi/parser-js/pull/214#discussion_r547948010) PR and it was exactly about `clonedeep`.

`channel.subscribe().messages('myMessage').originalPayload();` returns payload with `x-parser-*` props because I assume you use default AsyncAPI schema format for your payload. This means, [this parser](https://github.com/asyncapi/parser-js/blob/master/lib/asyncapiSchemaFormatParser.js) is used to parse your payload, and as you can see `x-parser-original-payload` is not added there. As a result, when you call [`originalPayload()`](https://github.com/asyncapi/parser-js/blob/master/lib/models/message.js#L31) then main `payload` prop is returned.

we could think of merging your usage of `clonedeep` into the default parser I mentioned above. But now we are back into my concern about performance. Would be great to know how would this additional clone operation affect the performance of the parser 🤔 I'm thinking here about large spec files with a lot of messages having individual payloads. Thoughts?

another workaround, you would need some step that filters out everything that starts with `x-parser-` 🤷🏼 
and for the record, I don't think that your approach with custom parser is wrong. It is ok. The only problem is that using it with a generator or react-component could not be so easy as I do not think we provide there any extension points for adding your own parser (afaik)

**Comment by JQrdan** [comment]
I agree that deep cloning here could easily very expensive with larger specs! It's definitely one way around our problem as is  doing a traverse to remove everything with `x-parser-`. I think there's also the larger question of the parser does some transformation of the payload (just adding extensions) but I don't want those extensions so doing by using `originalPayload()` I would expect to get the original payload that I defined without the extensions.

**Comment by JQrdan** [comment]
It's nice that there's the extensibility of the parser than we can opt into doing this cloneDeep ourselves but it feels very icky having a permanent 'work around' as this is only the case when there is an asyncapi schema (AFAIK)

**Comment by derberg** [comment]
@JQrdan that is true but because the schema is not changed/transformed like in case of others

**Comment by derberg** [comment]
@JQrdan you know what, I should not worry about something that we don't even measure. Please submit PR to fix it [here](https://github.com/asyncapi/parser-js/blob/master/lib/asyncapiSchemaFormatParser.js) and don't include the entire `lodash` as dependency but https://www.npmjs.com/package/lodash.clonedeep

I logged another issue to work on perf testing
