### ISSUE TITLE
Document how to fix randomly failing tests during development

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#558]
#### Reason/Context

Sometimes on Windows tests fail. We fixed it on CI but contributors are still affected on local development.

#### Description

- add an explanation to [Develop section in the Readme](https://github.com/asyncapi/parser-js#develop)
- this is why user needs to do https://github.com/asyncapi/parser-js/blob/master/.github/workflows/if-nodejs-pr-testing.yml#L23-L27
- explain when it is needed: "when you develop something in the parser and even though you did not make any changes affects tests, the tests are failing"

**Comment by Ruchip16** [comment]
Hey, @derberg I have documented the above points in the readme section in my forked repo, check once and let me know if that's what the issue is stating or if it needs any improvement further and I can make a final PR for the same.  
https://github.com/Ruchip16/parser-js/blob/master/README.md/#develop

**Comment by jonaslagoni** [comment]
Hey @Ruchip16, @derberg is on vacation at the moment, so I am jumping in if you don't mind?

Since you have already commited the changes to your branch, can I get you to create a PR? That way it is easier to see the changes you propose and we can review/discuss it directly 🙂 It's the easiest way to get feedback 👍 

Let me know if you have any issue creating one!

**Comment by Ruchip16** [comment]
Yess @jonaslagoni suree, I have made a PR, check it once and let me know if it needs any improvement further
