### ISSUE TITLE
improve error highlighting

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/parser-js#680]
#### Reason/Context
I have been using the studio to validate my AsyncAPI file.
the studio currently highlights all of the errors that cause the validation to fail; sometimes it's hard to find the root of the issue. 
consider this example: 
```yaml
asyncapi: 2.5.0
info:
  title: Flight Board
  version: 0.0.1
channels:
  /:
    publish:
      operationId: sendMessage
      message:
        oneOf:
          - $ref: '#/components/messages/getFlights'
components:
  messages:
    getFlights:
      summary: >-
        summary
      payload:
      type: object
```

If I pass it to the studio it will give me 9 errors which is confusing because it only has one error.

#### Possible Solution
As I see it, we are highlighting all of the errors that we get from the validator. and the validator will give errors for the whole yaml tree. we can filter the errors that we get from the validator and only highlight the branch that is causing the validation to fail.

**Comment by KhudaDad414** [comment]
I see what you mean. but current error highlighting is like saying: 
"Here is a list of errors:
<img width="661" alt="Screenshot 2022-11-24 at 12 59 05" src="https://user-images.githubusercontent.com/32505158/203790759-3e5440ae-4f79-44c8-8a0e-8f14011a2852.png">

90% of them don't make any sense. go figure it out yourself."
which in lots of cases is not that helpful.

**Comment by magicmatatjahu** [comment]
I agree, but I don't know if it would be possible to write an algorithm to remove the errors we don't need. AJV, as I wrote, shows all possible errors (for each encountered schema in a given place). Personally I don't touch this task, because it is probably impossible (in my opinion), but if someone has an idea, feel free to contribute.

That issue is more issue of `spec-json-schemas` side, not ajv or our parser.
