### ISSUE TITLE
[2.0.0] Circumventing the schema parsing

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#683]
#### Reason/Context
For the message payload, at times it will NOT be desired to convert a different schema format into the `SchemaInterface`, but rather have access to the raw schema or a specific format to interact with the native format.

In the old API you had `message.originalPayload()` but that is no longer available.

I also want to question whether the use-case is really there to still keep converting all message payloads into `SchemaInterface`? What would be the main reason? Abstraction or?

**Comment by magicmatatjahu** [comment]
If you wanna add new method, you need to update API there https://github.com/asyncapi/parser-api/blob/3a0c511d010c51d8632efb9a74cbfc77244335a7/docs/v1.md#message (you can make suggestion here https://github.com/asyncapi/parser-api/pull/71) and you can create PR with new method. However I think that `original()` method should be located in the `Schema` model - see PR https://github.com/asyncapi/spec/pull/797 - so I think that we should wait with adding new methods to the `Message` model, because probably `schemaFormat()` will be even deprecated. Also if you want, you can retrieve original payload from the `Message`'s extension:

```
message.extensions().get('x-parser-original-payload')
```

> I also want to question whether the use-case is really there to still keep converting all message payloads into SchemaInterface? What would be the main reason? Abstraction or?

if you want to use a schema data in an easy way then it's better to have one interface for it - generating models, generating documentation, validating payloads etc is much easier when you base it on JSON Schema and not on a dozen formats. Of course if someone wants to operate on the original format should can, but this is not the most common use case.

**Comment by jonaslagoni** [comment]
> Also if you want, you can retrieve original payload from the `Message`'s extension:

Is that the dereferenced payload model?

> if you want to use a schema data in an easy way then it's better to have one interface for it - generating models, generating documentation, validating payloads etc is much easier when you base it on JSON Schema and not on a dozen formats. Of course if someone wants to operate on the original format should can, but this is not the most common use case.

Yea that is true, it does make it easier to work with in the basic use-cases. I can't recall, do you need to provide a schema parser for you to access the raw schema and the parser to work? (I can check later)

**Comment by magicmatatjahu** [comment]
> Is that the dereferenced payload model?

If it's JSON Schema, yes, it is.

> Yea that is true, it does make it easier to work with in the basic use-cases. I can't recall, do you need to provide a schema parser for you to access the raw schema and the parser to work? (I can check later)

What do you have in mind? If you have Avro format then you must have a parser given to the parser for Avro schemas, otherwise the parser will throw you an error and the schema is unsupported.

**Comment by smoya** [comment]
@jonaslagoni is this issue still applying?

**Comment by smoya** [comment]
still relevant IMHO
