### ISSUE TITLE
Parser inconsistently applying additionalProperties schema validation

### ISSUE THREAD

**Issue by jamescrowley** [asyncapi/parser-js#75]
#### Describe the bug

Depending on how the schema is constructed, additionalProperties is sometimes allowed to deviate from the schema without a parse error.

#### How to Reproduce

The following is parsed successfully:

```
asyncapi: 2.0.0
info:
  title: Demo API
  version: '2-0-0'

channels:
  /someChannel:
    publish:
      operationId: someOp
      message:
        payload:
          type: object
          additionalProperties: [invalid_array]
```

However, the following is rejected:

```
asyncapi: 2.0.0
info:
  title: Demo API
  version: '2-0-0'

channels:
  /someChannel:
    publish:
      operationId: someOp
      message:
        payload:
          $ref: #/components/schemas/someOp
components:
  schemas:
    someOp:
      type: object
      additionalProperties: [invalid_array]
```

#### Expected behavior
I would expect the parser to reject both formats, given it does not comply with the schema

**Comment by derberg** [comment]
I think the error is related to an error in json schema, doesn't matter if payload goes directly to a message under channel or components. 

json schema, just says `"payload": {}` and in my opinion json schema should say 
```
"payload": {
                  "$ref": "#/definitions/schema"
                },
```

I'm not sure though as the spec in https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#fixed-fields-14 says and says `Definition of the message payload. It can be of any type but defaults to Schema object.`. I'm not really 100% sure what `but defaults to Schema object` means really.

@fmvilas can you please share some insights

**Comment by fmvilas** [comment]
The error is in the parser itself. It's not using a schema parser when it's found under `payload`: https://github.com/asyncapi/parser-js/blob/master/lib/index.js#L5.

> json schema, just says "payload": {} and in my opinion json schema should say
>
> ```
> "payload": {
>   "$ref": "#/definitions/schema"
> },
> ```

This would be incorrect for other schema formats like RAML, Avro, or OpenAPI Schema Objects. In JSON Schema, assigning a value of `{}` is like saying you don't want to validate it. It can be anything.

> I'm not really 100% sure what `but defaults to Schema object means really`.

This has to do with the [schemaFormat](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#messageObjectSchemaFormat) property of the Message Object. By default, we expect the payload to be a [Schema Object](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#schemaObject).

**Comment by derberg** [comment]
@fmvilas thanks a bunch, obviously it all makes sense, thanks for the explanation 

I think though we have 2 bugs there. One is also related explicitly to YAML format because when I check examples from this issue I get:
```
Something went wrong:
Error: Cannot read property 'kind' of null
    at parse (/Users/wookiee/Documents/sources/generator/node_modules/@asyncapi/parser/lib/parser.js:123:11)
    at async Generator.generateFromString (/Users/wookiee/Documents/sources/generator/lib/generator.js:239:21)
    at async /Users/wookiee/Documents/sources/generator/cli.js:149:9
```

but when I convert it to json and try again, I get proper error:
```
Something went wrong:
Error: There were errors validating the AsyncAPI document.
    at parse (/Users/wookiee/Documents/sources/generator/node_modules/@asyncapi/parser/lib/parser.js:113:23)
    at async Generator.generateFromString (/Users/wookiee/Documents/sources/generator/lib/generator.js:239:21)
    at async /Users/wookiee/Documents/sources/generator/cli.js:149:9
```

error is somewhere here https://github.com/fmvilas/pseudo-yaml-ast/blob/master/src/index.js#L116. I'll work on PR

**Comment by derberg** [comment]
@fmvilas have a look at https://github.com/fmvilas/pseudo-yaml-ast/pull/1

I will now dig into original problem

**Comment by fmvilas** [comment]
Done and published to npm, version 0.3.1 👍

**Comment by derberg** [comment]
@fmvilas 

> The error is in the parser itself. It's not using a schema parser when it's found under payload: https://github.com/asyncapi/parser-js/blob/master/lib/index.js#L5.

You have me lost here. I checked and proper schema parser is invoked, but the problem is that this empty function is called https://github.com/asyncapi/parser-js/blob/master/lib/index.js#L3. There is basically no implementation of the function that parses and validates `application/vnd.aai.asyncapi;version=2.0.0` or I'm blind 😄 and it is of course possible 😄 

what I'm saying is that the message payload and other info are passed to this empty function https://github.com/asyncapi/parser-js/blob/master/lib/parser.js#L173-L175 but of course nothing happens

**Comment by fmvilas** [comment]
Yeah, sorry for the confusion. The `noop` (no operation) function there is on purpose because message payloads are being validated when we run Ajv. Therefore, no need to run message parsers.

**Comment by derberg** [comment]
@fmvilas this makes much more sense why `noop` is there. So we basically do not need an extra parser because the Ajv is doing it based on the JSON Schema of AsyncAPI, right? aren't we now at the starting point then 😄 

if we validate with Ajv and the schema says `"payload": {}` then what is your suggestion to fix this bug?

**Comment by fmvilas** [comment]
Oh, that's true 😅 We should then implement a default schema parser (instead of the noop) that internally will use Ajv to validate against [this](https://github.com/asyncapi/asyncapi-node/blob/master/schemas/2.0.0.json#L355).

**Comment by derberg** [comment]
ufff, I was afraid I'm not getting something 😄 now all clear, will work on it
