### ISSUE TITLE
New parser vs Old parser -> how to do `traverseSchemas` in new api

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#832]
Old API had https://github.com/asyncapi/parser-js/blob/master/src/old-api/asyncapi.ts#L157

I could do `asyncapi.traverseSchemas(generateDiagram);` on my parsed AsyncAPI document and iterate over all schemas of the document and pass my custom function inside.

There is nothing about it in https://github.com/asyncapi/parser-js/blob/master/docs/migrations/v1-to-v2.md

I think it is bug, either docs or ?

**Comment by derberg** [comment]
@smoya but the function you refer to is different, I saw it, but it traverses entire document, the one I used was just for schemas

**Comment by smoya** [comment]
> @smoya but the function you refer to is different, I saw it, but it traverses entire document, the one I used was just for schemas

It works in the same way. It iterates over the types you pass in the function, which by default, are the [Schema types](https://github.com/asyncapi/parser-js/blob/6940b2bac0977a9952f3ac746804670a4104161b/src/iterator.ts#L19).

You have an example of usage [here](https://github.com/asyncapi/parser-js/blob/6940b2bac0977a9952f3ac746804670a4104161b/src/custom-operations/anonymous-naming.ts#L63-L70).

**Comment by derberg** [comment]
@smoya correct me if I'm wrong but I don't think it is exposed by the library.

**Comment by derberg** [comment]
@smoya pingy pongy

**Comment by jonaslagoni** [comment]
😆

**Comment by smoya** [comment]
@derberg You are right, we would need to add the proper export to the [src/index.ts](https://github.com/asyncapi/parser-js/blob/next-major-spec/src/index.ts) file.

Regarding this delay in my answer, I can swear to you I "answered" this after your last ping. It feels so embarrassed, the only thing that could happen is that my old laptop (replaced 2 weeks ago) was behaving **very bad** in terms of lags (keyboard vs screen, etc) because of high temp in the CPU (caused by a known issue in my old model). Maybe I believed I hit the "Comment" button and never did.
I'm very sorry.
