### ISSUE TITLE
Add method .hasMessages()

### ISSUE THREAD

**Issue by WaleedAshraf** [asyncapi/parser-js#84]
Add method `asyncapi.hasMessages()` like we have others, `asyncapi.hasChannels()`.
This will be used to check if messages are defined, and then show them in a separate section.

To be used here:
https://github.com/asyncapi/html-template/pull/31#pullrequestreview-422044695

Related PR: https://github.com/asyncapi/html-template/pull/31

**Comment by derberg** [comment]
@fmvilas what is you view on this. `asyncapi.hasChannels()` and `asyncapi.hasServers()` make sense as channels and servers are root elements, messages are not. But I do not think we are super strict in models here right? because we already have `asyncapi.allMessages()` then why not having `asyncapi.hasMessages()`? right?

**Comment by fmvilas** [comment]
It totally makes sense, yes. Actually, the purpose of the parser is to eventually offer an abstract infterface that's independent of the AsyncAPI document structure. This is a good example.

**Comment by fmvilas** [comment]
Yes. We can probably have another issue to target all those missing methods. Not necessarily for v1 though.

**Comment by derberg** [comment]
@fmvilas yeap, added https://github.com/asyncapi/parser-js/issues/88
