### ISSUE TITLE
Message ID doesn't exist on reply level

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/parser-js#873]
When using the request-reply pattern, and you're trying to retrieve the reply() messages, the parser is returning the wrong message ID for some reason. 

Here's what I mean by wrong messages. In the example below, I expect the parser to return the messageID of the messages available in the reply object, but instead, all I get is the index(`integer`) of the message as ID

```
operations:
    requestCosting:
      action: receive
      channel: 
        $ref: '#/channels/costingRequest'
      reply:
        channel: 
          $ref: '#/channels/costingResponse'
        messages:
          - $ref: "#/components/messages/costingResponse"
```

cc @smoya @fmvilas

**Comment by smoya** [comment]
@AceTheCreator could you please provide a code snippet of what you are executing and the output? Thank you!

**Comment by smoya** [comment]
Can this be somehow related to the issue under https://github.com/asyncapi/parser-js/issues/856 @jonaslagoni ?

**Comment by jonaslagoni** [comment]
> The 0 returned by id is because you in this case have an array of messages where this one is the first index.
undefined is returned because, well, the message object does not contain a messageId property.

Whether this behavior is the right and expected behavior, we will have to chime in @magicmatatjahu 😄

**Comment by jonaslagoni** [comment]
The problem then is the way references are currently being handled, is NOT to replace the reference in operations to channels and messages with the already resolved object that we created for the instance in the channel. 

We simply don't have access to the key in the key/value pair that is being referenced. Therefore the ONLY possible solution we can do is this with the tooling we have at hand.

Otherwise, we have to create our own reference tooling that can resolve partial references and manually control what instance should be returned.

**Comment by derberg** [comment]
Just kind reminder that we knew that [using $ref everywhere will have a side effect that it will he harder to get the id of the element](https://github.com/asyncapi/spec/issues/829) and that we will have to [hook into dereferencing process](https://github.com/asyncapi/spec/issues/663#issuecomment-1163050817). So instead of waiting for or working on completely new tool that handles references, parser should grab id from the reference, and put in some extension like `x-parser-refId` or whatever

**Comment by smoya** [comment]
> So instead of waiting for or working on completely new tool that handles references, parser should grab id from the reference, and put in some extension like `x-parser-refId` or whatever

It is not a trivial thing. Dereference is not handled by the parser directly but by [@stoplight/json-ref-resolver](https://www.npmjs.com/package/@stoplight/json-ref-resolver). The fact we would need to get access to the surrounding of the referenced object in order to get the key of the map if exists makes it even harder.

**Comment by smoya** [comment]
Made a working POC about getting the ID from the JSON Pointer in the reference for `reply.chanel` and `reply.messages[]`: https://github.com/asyncapi/parser-js/pull/895

Do you think it makes sense in that way? Is that what you meant @derberg ?

**Comment by derberg** [comment]
@smoya I think `objectIdFromJSONPointer` is complex enough that it deserves unit tests that can clearly explain what works and what doesn't work 😓

**Comment by smoya** [comment]
> @smoya I think `objectIdFromJSONPointer` is complex enough that it deserves unit tests that can clearly explain what works and what doesn't work 😓 

It is just a draft, a proof of concept. It takes the last part of the pointer as the Id.

**Comment by derberg** [comment]
sounds good to me

**Comment by jonaslagoni** [comment]
Should be solved, feel free to re-open if you still encounter it 🙂
