### ISSUE TITLE
Parser returns `undefined` when there's bindings in message 

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/parser-js#877]
#### Describe the bug
The Parser fails to work when I have message bindings in my asyncapi v3 file

#### How to Reproduce
Add a binding to any of your messages

You can use this adeo example https://github.com/asyncapi/spec/blob/next-major-spec/examples/adeo-kafka-request-reply.yml

#### Expected behavior
If it's not gonna work which I expect it to work, then I expect the Parser to return an error instead of `undefined` 

cc @smoya

**Comment by kouzitech** [comment]
I have fixed this issue in PR #1168

The root cause was that the `bindings()` function in `v3/mixins.ts` iterates over all entries of the bindings object, including `$ref` keys. When bindings contains a `$ref` like `{"$ref": "#/components/messageBindings/myBindings"}`, the `$ref` was being treated as a protocol name, causing the parser to crash or return `undefined`.

The fix filters out keys starting with `$` before processing binding entries.

I am participating in the MICROGRANT Program 2026-06 #1167

**Comment by princerajpoot20** [comment]
@kouzitech Please refer to these microgrant program rules https://github.com/asyncapi/community/blob/master/docs/010-contribution-guidelines/microgrant-program.md

**Comment by kouzitech** [comment]
@princerajpoot20 Thank you for pointing me to the Microgrant Program rules. I have read them carefully now.

I understand that I should wait for the `microgrant` label to be added to this issue before expressing interest and submitting a PR. I apologize for jumping ahead of the process.

I would like to formally express my interest in working on this issue (#877) and #878 as a set, should they be accepted into an upcoming Microgrant round. My approach would be:

1. For #877: Filter out `$ref` keys in the `bindings()` function in `v3/mixins.ts` to prevent `$ref` from being treated as a protocol name
2. For #878: Modify `createUncaghtDiagnostic()` to properly handle non-Error objects in the catch block

I am a third-category participant (no prior merged PRs in AsyncAPI). Looking forward to contributing properly through the program.
