### ISSUE TITLE
Add validation of message examples

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#99]
#### Reason/Context
Have a mechanism that validates examples of payload. Examples are used as part of rendered docs and by mocking tools and should be 100% accurate.

#### Description
Ajv doesn't want to be responsible for [examples](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.5) validation, but it could be done with Ajv plugin, all details [here](https://github.com/ajv-validator/ajv/issues/962#issuecomment-469038167). I did not find any available plugin at the moment.
Knowing that Ajv is now under development to support the latest JSON Schema, and it affects Ajv architecture as the plan is to rewrite with TypeScript, I would suggest waiting until they are done with it.

**Comment by derberg** [comment]
This one is still very much needed. Should not be complicated because it is about comparing data against schema, and ajv is already used in the parser

**Comment by Weffe** [comment]
+1 To validating examples. It would be a nice to have and a quick way to get feedback on the schema and the example for it.

**Comment by derberg** [comment]
@Weffe would it be something you could help with contributing, I can guide you

**Comment by MerzDaniel** [comment]
We are also interested in the context of writing tests or even in the production code itself it makes sense to validate event payload types. 

For our rest api which is documented in OpenApi3 we use this library: https://www.npmjs.com/package/api-schema-builder. It provides a easy to use validation mechanism which we use as part of our test infrastructure. 

E.g. the schema which is created by this library could provide a `validation()` function.
```
test() {
  // do some things
  // ...
  // validate
  const message = await getMessage()
  schema.validate(channel, 'publish', message.payload)
}
```

**Comment by magicmatatjahu** [comment]
@MerzDaniel Hello! Thanks for comment! 

Please note that this issue is related to the validation of the examples not after the validation of the specification but during the validation, this means that the user passing the specification to the parser should receive errors/information regarding badly formatted examples for message's payload and headers. As far as your idea is concerned I recommend to create separate issue because it concerns two different things :) Sooner or later we will need a similar feature so I would really ask you to create a separate issue, thanks!

**Comment by magicmatatjahu** [comment]
Still valid and it will be resolved in the v2 version.

**Comment by magicmatatjahu** [comment]
Issue is resolved in v2 ParserJS - now in https://github.com/asyncapi/parser-js/tree/next-major branch
